version: '3.7'
services:
  # simple myself setup
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiapdb
      MYSQL_USER: brugrue
      MYSQL_PASSWORD: root
      TZ: "America/Bahia"
    volumes:
      - ./mysql/script:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql

  # grafana used for graphing mysql data
  grafana:
    image: grafana/grafana:5.1.0
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.99.101
      - GF_SECURITY_ADMIN_PASSWORD=root
      - TZ=America/Bahia
    ports:
      - '3000:3000'
    user: "104"