version: '3.7'
services:
  # simple myself setup
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
      MYSQL_USER: brugrue
      MYSQL_PASSWORD: root

  # grafana used for graphing mysql data
  grafana:
    image: grafana/grafana:5.1.0
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.99.101
      - GF_SECURITY_ADMIN_PASSWORD=root
    ports:
      - '3000:3000'
    user: "104"